services:
  db:
    container_name: saskfund_db
    image: postgres:17.4
    restart: always
    env_file:
      - .env     
    ports:
      - '5431:5432'
    volumes:
      - saskfund_data:/var/lib/postgresql/data    

  pgadmin:
    container_name: saskfund_pgadmin
    image: dpage/pgadmin4:8.14
    restart: always
    env_file:
      - .env    
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  saskfund_data:
  pgadmin_data:
  

